In [1]:
#Câu 1:
import numpy as np
from numpy.linalg import norm
from math import degrees, acos
A = np.array([2, -1, 3, 0])
B = np.array([1, 4, -2, 5])
C = np.array([[1, 2, -1],[0, 3, 4], [2, -1, 0]])
tong = A + B
tich_so = 3 * A - 2 * B
print("a) Tổng A + B:", tong)
print("   Tích số 3A - 2B:", tich_so)
dot_product = np.dot(A, B)
cos_theta = dot_product / (norm(A) * norm(B))
goc_do = round(degrees(acos(cos_theta)), 3)
print("b) Tích vô hướng A · B:", dot_product)
print("   Góc giữa A và B (độ):", goc_do)
CT = C.T
CTC = CT @ C
print("c) Ma trận C^T * C:\n", CTC)


a) Tổng A + B: [3 3 1 5]
   Tích số 3A - 2B: [  4 -11  13 -10]
b) Tích vô hướng A · B: -8
   Góc giữa A và B (độ): 108.376
c) Ma trận C^T * C:
 [[ 5  0 -1]
 [ 0 14 10]
 [-1 10 17]]


In [2]:
#Câu 2:
import numpy as np
M = np.array([[1, 2, 3, 0], [4, 5, 6, 1], [7, 8, 9, 2], [0, 1, 1, 0]])
N = np.array([[0, 1, 2, 3], [4, 5, 6, 7],  [8, 9, 10, 11], [12, 13, 14, 15]])
tich_MN = M @ N
print("a) Tích M × N:\n", tich_MN)
try:
    dinh_thuc_M = round(np.linalg.det(M), 3)
    print("b) Định thức của M:", dinh_thuc_M)
except np.linalg.LinAlgError:
    print("b) Không thể tính định thức vì M không phải là ma trận vuông")
hang_N = np.linalg.matrix_rank(N)
print("c) Hạng của ma trận N:", hang_N)

a) Tích M × N:
 [[ 32  38  44  50]
 [ 80  96 112 128]
 [128 154 180 206]
 [ 12  14  16  18]]
b) Định thức của M: 0.0
c) Hạng của ma trận N: 2


In [3]:
#Câu 3:
import numpy as np
P = np.array([[2, 1, 0, 1],  [0, 3, 1, -1],[1, 0, 4, 2],[0, 1, 0, 3]])
b = np.array([4, 7, 9, 5])
try:
    P_inv = np.linalg.inv(P)
    print("a) Ma trận nghịch đảo của P:\n", np.round(P_inv, 3))
except np.linalg.LinAlgError:
    print("a) Ma trận P không khả nghịch (det = 0)")
x = P_inv @ b
print("b) Nghiệm của hệ phương trình là:\n", np.round(x, 3))
b_check = P @ x
print("c) P @ x =\n", np.round(b_check, 3))
print("Vector hằng số b =\n", b)
print("✅ Kiểm tra: ", np.allclose(b_check, b))


a) Ma trận nghịch đảo của P:
 [[ 0.488 -0.093  0.023 -0.209]
 [ 0.035  0.279 -0.07   0.128]
 [-0.116  0.07   0.233 -0.093]
 [-0.012 -0.093  0.023  0.291]]
b) Nghiệm của hệ phương trình là:
 [0.465 2.105 1.651 0.965]
c) P @ x =
 [4. 7. 9. 5.]
Vector hằng số b =
 [4 7 9 5]
✅ Kiểm tra:  True


In [4]:
#Câu 4:
import numpy as np
Q = np.array([[4, -1, 0], [1,  3, -2], [0,  1,  2]])
eigenvalues, eigenvectors = np.linalg.eig(Q)
print("a) Các giá trị riêng (eigenvalues):")
print(np.round(eigenvalues, 3))
print("\nb) Các vector riêng tương ứng (mỗi cột là 1 vector):")
print(np.round(eigenvectors, 3))
norm_vectors = []
print("\nc) Vector riêng sau khi chuẩn hóa (độ dài = 1):")
for v in eigenvectors.T:
    norm_v = v / np.linalg.norm(v)
    norm_vectors.append(norm_v)
    print(np.round(norm_v, 3))


a) Các giá trị riêng (eigenvalues):
[3.453+0.j    2.773+1.468j 2.773-1.468j]

b) Các vector riêng tương ứng (mỗi cột là 1 vector):
[[ 0.833+0.j    -0.262-0.314j -0.262+0.314j]
 [ 0.455+0.j    -0.782+0.j    -0.782-0.j   ]
 [ 0.313+0.j    -0.22 +0.417j -0.22 -0.417j]]

c) Vector riêng sau khi chuẩn hóa (độ dài = 1):
[0.833+0.j 0.455+0.j 0.313+0.j]
[-0.262-0.314j -0.782+0.j    -0.22 +0.417j]
[-0.262+0.314j -0.782+0.j    -0.22 -0.417j]


In [5]:
#Câu 5
import numpy as np
# a)
R = np.array([[1, -2, 3],[2,  0, 1], [-1, 1, 4]])
b = np.array([10, 8, 7])
x = np.linalg.solve(R, b)
print("a) Nghiệm của hệ phương trình Rx = b là:")
print(np.round(x, 3))
# b)
det_R = np.linalg.det(R)
print("\nb) Định thức của R:", round(det_R, 3))
if det_R != 0:
    R_inv = np.linalg.inv(R)
    print("R là khả nghịch. Ma trận nghịch đảo của R là:")
    print(np.round(R_inv, 3))
    x_check = R_inv @ b
    print("\nNghiệm tính bằng R⁻¹ @ b:")
    print(np.round(x_check, 3))
    print("\nHai nghiệm có bằng nhau không?", np.allclose(x, x_check))
else:
    print("R không khả nghịch (det = 0), không thể tính R⁻¹.")

# c)
fro_norm = np.linalg.norm(R, 'fro')
print("\nc) Chuẩn Frobenius của ma trận R:", round(fro_norm, 3))

a) Nghiệm của hệ phương trình Rx = b là:
[2.783 0.043 2.435]

b) Định thức của R: 23.0
R là khả nghịch. Ma trận nghịch đảo của R là:
[[-0.043  0.478 -0.087]
 [-0.391  0.304  0.217]
 [ 0.087  0.043  0.174]]

Nghiệm tính bằng R⁻¹ @ b:
[2.783 0.043 2.435]

Hai nghiệm có bằng nhau không? True

c) Chuẩn Frobenius của ma trận R: 6.083
