In [2]:
#Bài 1:
#Tích vô hướng, trực giao và ứng dụng
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
tich = np.inner(a, b)
print(tich)
print(np.dot(a, b))

32
32


In [3]:
#Độ dài/chuẩn của vector:
import numpy as np
import math
from scipy import linalg

a = np.array([1, 2, -3])

def chuan(vec, k):
    return sum(abs(x)**k for x in vec)**(1/k)
print(np.linalg.norm(a))
print(np.linalg.norm(a, 1))
print(chuan(a, 1))
print(np.linalg.norm(a, 1))
print(chuan(a, 2))
print(np.linalg.norm(a, 2))
print(chuan(a, 3))
print(np.linalg.norm(a, 3))
print(chuan(a, 1000))
print(np.linalg.norm(a, 1000))
print(linalg.norm(a))
print(linalg.norm(a, 100))
print(linalg.norm(a, 1000))

3.7416573867739413
6.0
6.0
6.0
3.7416573867739413
3.7416573867739413
3.3019272488946263
3.3019272488946263
1.0442214818467515
inf
3.7416573867739413
3.0
inf


/usr/local/lib/python3.11/dist-packages/numpy/linalg/_linalg.py:2780: RuntimeWarning: overflow encountered in power
  absx **= ord


In [23]:
#bài 2:
import numpy as np

m = 10
v1 = np.array([5, -4, 3])
v2 = np.array([4, 3, -2])
v3 = np.array([-4, -3, -1])
v4 = np.array([-9, 8, 6])
mi = np.array([2, 5, 2, 1])
M = np.array([v1, v2, v3, v4])
MT = M.transpose()
v = (1.0 / m) * MT.dot(mi)
print(MT)
print(v)

[[ 5  4 -4 -9]
 [-4  3 -3  8]
 [ 3 -2 -1  6]]
[1.3 0.9 0. ]


In [24]:
#Bài 3:
import numpy as np

A = np.array([[0.998, 0.136],
              [0.002, 0.864]])

v0 = np.array([[0.95],
               [0.05]])
A100 = np.linalg.matrix_power(A, 100)
v100 = A100 @ v0
print(A100)
print(v100)

[[0.98550725 0.9855069 ]
 [0.01449275 0.0144931 ]]
[[0.98550723]
 [0.01449277]]


In [25]:
#thử nghiệm giải hệ trên bằng gói sympy:
import sympy as sym

x, y = sym.symbols('x y')
xy = sym.Matrix([x, y])
A = sym.Matrix([[1, -68], [1, 1]])
v = sym.Matrix([0, 1])
nghiem = sym.solve([A * xy - v])
print(sym.pretty(nghiem))

⎧   68         ⎫
⎨x: ──, y: 1/69⎬
⎩   69         ⎭


In [26]:
#Trị riêng và vector riêng của ma trận
# kiểm lại phát biểu:
import sympy as sym

A = sym.Matrix([[1, 6], [5, 2]])
u = sym.Matrix([6, -5])

kq = A * u
kq_so_voi = -4 * u

print("A * u =", kq)
print("-4 * u =", kq_so_voi)
print("A*u == -4*u ?", kq == kq_so_voi)


A * u = Matrix([[-24], [20]])
-4 * u = Matrix([[-24], [20]])
A*u == -4*u ? True


In [27]:
# Tính trị riêng bằng gói thư viện sympy
import sympy as sym
x, y, Lambda = sym.symbols('x y Lambda')
I = sym.eye(2)
A = sym.Matrix([[2, 3], [3, -6]])
phuongtrinh = sym.Eq(sym.det(Lambda * I - A), 0)
nghiem = sym.solve(phuongtrinh)
print([sym.N(val, 4) for val in nghiem])
print(sym.pretty(nghiem))

[-7.000, 3.000]
[-7, 3]


In [28]:
#.Ứng dụng của trị riêng và vector riêng
import numpy as np
from numpy import linalg as LA

A = np.array([[2, 3], [3, -6]])
D = np.array([[-7, 0], [0, 3]])
P = np.array([[-1.0/3, 3], [1, 1]])
P1 = LA.inv(P)
print(P1)
print(A.dot(P))
print(P.dot(D))
print(D @ D)
print(np.linalg.matrix_power(D, 1000))
print(P @ np.linalg.matrix_power(D, 1000) @ P1)

[[-0.3  0.9]
 [ 0.3  0.1]]
[[ 2.33333333  9.        ]
 [-7.          3.        ]]
[[ 2.33333333  9.        ]
 [-7.          3.        ]]
[[49  0]
 [ 0  9]]
[[-5479429532463080511                    0]
 [                   0  6203307696791771937]]
[[ 5.03503397e+18  3.50482117e+18]
 [ 3.50482117e+18 -4.31115581e+18]]


# **Bài Tập Chương**

In [29]:
#Câu 1:
import numpy as np
import math

a = np.array([1, 2, 3])
mag1 = np.sqrt(a.dot(a))
print(mag1)
mag2 = np.sqrt(a @ a)
print(mag2)
mag3 = np.sqrt(np.inner(a, a))
print(mag3)
mag = lambda x: math.sqrt(sum(i ** 2 for i in x))
print(mag(a))
#đáp án a chuẩn nhất dù cả 4 đều đúng

3.7416573867739413
3.7416573867739413
3.7416573867739413
3.7416573867739413


In [30]:
#câu 2:
import numpy as np
from math import acos, degrees
u = np.array([1, 2, 3])
v = np.array([4, 5, 6])
# a. Tính khoảng cách giữa 2 vector u và v: ||u - v||
khoang_cach = np.linalg.norm(u - v)
print("a. Khoảng cách ||u - v|| =", khoang_cach)
# b. Tính góc θ giữa u và v:
tich_vo_huong = np.dot(u, v)
chuan_u = np.linalg.norm(u)
chuan_v = np.linalg.norm(v)
cos_theta = tich_vo_huong / (chuan_u * chuan_v)
theta = acos(cos_theta)        # kết quả tính theo radian
print("b. Góc θ (radian) =", theta)
print("b. Góc θ (độ) =", degrees(theta))
# c. Phép chiếu trực giao p của u lên v:
phan_so = np.dot(u, v) / np.dot(v, v)
p = phan_so * v
print("c. Vector chiếu p =", p)


a. Khoảng cách ||u - v|| = 5.196152422706632
b. Góc θ (radian) = 0.2257261285527342
b. Góc θ (độ) = 12.933154491899135
c. Vector chiếu p = [1.66233766 2.07792208 2.49350649]
