In [1]:
#Câu 1:
#khai báo
import numpy as np
A, B = np.array([3, -2, 1, 4]), np.array([-1, 5, 0, 2])
C = np.array([[2, -1, 3], [1, 4, -2], [0, 2, 5]])
# a)
print("C1.a A + B =", A + B)
print("C1.a 2A + 3B =", 2*A + 3*B)
# b)
tich_vo_huong = np.dot(A, B)
do_dai_A = np.linalg.norm(A)
do_dai_B = np.linalg.norm(B)
cos_goc = tich_vo_huong / (do_dai_A * do_dai_B)
goc_do = round(np.degrees(np.arccos(cos_goc)), 3)
print("C1.b A · B =", tich_vo_huong)
print("C1.b Góc giữa A và B =", goc_do, "độ")
# c)
print("C1.c C nhân Cᵀ =\n", C @ C.T)


C1.a A + B = [2 3 1 6]
C1.a 2A + 3B = [ 3 11  2 14]
C1.b A · B = -5
C1.b Góc giữa A và B = 99.594 độ
C1.c C nhân Cᵀ =
 [[14 -8 13]
 [-8 21 -2]
 [13 -2 29]]


In [2]:
#Câu 2:
#Khai báo
M = np.array([[2, -1, 3, 0], [1, 4, -2, 5], [0, 2, 6, -3], [-1, 0, 1, 4]])
N = np.array([[1, 3, -2, 0], [4, -1, 5, 2], [0, 2, 3, -1], [-3, 1, 0, 4]])
# a)
print("C2.a M × N =\n", M @ N)
# b)
print("C2.b Định thức M =", np.linalg.det(M))
# c)
print("C2.c Hạng của N =", np.linalg.matrix_rank(N))


C2.a M × N =
 [[ -2  13   0  -5]
 [  2   0  12  30]
 [ 17   7  28 -14]
 [-13   3   5  15]]
C2.b Định thức M = 409.00000000000017
C2.c Hạng của N = 4


In [7]:
#Câu 3
import numpy as np
# Khai bá0
P = np.array([[3, -1, 0, 2],
              [1,  4, -2, 0],
              [0,  1,  5, -1],
              [2,  0,  1, 3]])
b = np.array([6, 8, 3, 7])
# a)
if np.linalg.det(P) != 0:
    P_inv = np.linalg.inv(P)
    print("C3.a Nghịch đảo của P:\n", P_inv)
else:
    print("C3.a P không có nghịch đảo (det = 0)")
# b)
if np.linalg.det(P) != 0:
    x = np.linalg.solve(P, b)
    print("C3.b Nghiệm x =", x)
else:
    x = None
    print("C3.b Không giải được vì P không khả nghịch")
# c)
if x is not None:
    print("C3.c P · x = ", P @ x)

C3.a Nghịch đảo của P:
 [[ 0.5         0.1         0.1        -0.3       ]
 [-0.14285714  0.2         0.05714286  0.11428571]
 [-0.03571429 -0.05        0.16428571  0.07857143]
 [-0.32142857 -0.05       -0.12142857  0.50714286]]
C3.b Nghiệm x = [2.         1.71428571 0.42857143 0.85714286]
C3.c P · x =  [6. 8. 3. 7.]


In [4]:
# Câu 4:
Q = np.array([[5, -2, 1], [0, 3, -1], [2, 0, 4]])
# a)
gt_rieng = np.linalg.eigvals(Q)
print("C4.a Giá trị riêng:", gt_rieng)
# b)
vec_rieng = np.linalg.eig(Q)[1]
print("C4.b Vector riêng:\n", vec_rieng)
# c)
vec_chuanhoa = np.array([v / np.linalg.norm(v) for v in vec_rieng.T])
print("C4.c Vector riêng chuẩn hóa:\n", vec_chuanhoa)

C4.a Giá trị riêng: [6.3553014+0.j         2.8223493+1.07730381j 2.8223493-1.07730381j]
C4.b Vector riêng:
 [[ 0.74846013+0.j         -0.37423006+0.34234215j -0.37423006-0.34234215j]
 [-0.18941773+0.j          0.09470887+0.57433055j  0.09470887-0.57433055j]
 [ 0.63555359+0.j          0.63555359+0.j          0.63555359-0.j        ]]
C4.c Vector riêng chuẩn hóa:
 [[ 0.74846013+0.j         -0.18941773+0.j          0.63555359+0.j        ]
 [-0.37423006+0.34234215j  0.09470887+0.57433055j  0.63555359+0.j        ]
 [-0.37423006-0.34234215j  0.09470887-0.57433055j  0.63555359-0.j        ]]


In [5]:
# Câu 5:
R = np.array([[4, -1, 2], [1, 3, -2], [0, 2, 5]])
b5 = np.array([12, 5, 9])
# a)
x5 = np.linalg.solve(R, b5)
print("C5.a Nghiệm hệ Rx = b:", x5)
# b)
if np.linalg.det(R) != 0:
    R_nghich = np.linalg.inv(R)
    print("C5.b R⁻¹ · b =", R_nghich @ b5)
else:
    print("C5.b R không khả nghịch")

# c)
print("C5.c Chuẩn Frobenius của R =", np.linalg.norm(R, 'fro'))

C5.a Nghiệm hệ Rx = b: [2.78823529 1.52941176 1.18823529]
C5.b R⁻¹ · b = [2.78823529 1.52941176 1.18823529]
C5.c Chuẩn Frobenius của R = 8.0
