In [ ]:
#Bài 1:
from scipy import linalg
import numpy as np
a = np.array([1, 2, 3])
b = np.array([[1, 2, 3], [4, 5, 6]])
c = np.array([[(0.5, 1.5, 10), (3, 2, 1)], [(6, 5, 4), (7, 8, 9)]])

A = np.matrix(np.random.random((2, 2)))
B = np.asmatrix(b)
C = np.asmatrix(np.random.random((10, 5)))
D = np.asmatrix([[4, 3], [2, 6]])

F = np.eye(3, k=1)
print(F)

F = np.eye(3, k=0)
print(F)

F = np.eye(3, k=-1)
print(F)

print(np.linalg.matrix_rank(C))

print(A.I)
print(linalg.inv(A))

print(linalg.det(A))
print(A.T)
print(A.H)

b_vec = np.array([1, 2])
print(linalg.solve(D, b_vec))
E = np.asmatrix(a).T
print(E)
print(linalg.lstsq(F, E))
print(np.add(A, D))
print(np.subtract(A, D))
print(np.divide(A, D))

print(A @ D)
print(np.multiply(D, A))
print(np.dot(A, D))
print(np.vdot(A, D))
print(linalg.expm(A))
print(linalg.logm(A))

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]
5
[[-303.85472318  286.30368156]
 [ 122.28994791 -114.08692814]]
[[-303.85472318  286.30368156]
 [ 122.28994791 -114.08692814]]
-0.00288841751824386
[[0.32953068 0.35322443]
 [0.82696457 0.87765931]]
[[0.32953068 0.35322443]
 [0.82696457 0.87765931]]
[0.         0.33333333]
[[1]
 [2]
 [3]]
(array([[2.],
       [3.],
       [0.]]), array([], dtype=float64), 2, array([1., 1., 0.]))
[[4.32953068 3.82696457]
 [2.35322443 6.87765931]]
[[-3.67046932 -2.17303543]
 [-1.64677557 -5.12234069]]
[[0.08238267 0.27565486]
 [0.17661221 0.14627655]]
[[2.97205187 5.95037946]
 [3.16821632 6.32562912]]
[[1.31812273 2.48089371]
 [0.70644886 5.26595583]]
[[2.97205187 5.95037946]
 [3.16821632 6.32562912]]
[[1.31812273]]
[[1.64242461 1.60652261]
 [0.68619993 2.70725987]]
[[-4.33178072+2.28121106j  4.24929106-2.14361297j]
 [ 1.81501537-0.91560932j -1.51526578+0.86038159j]]


In [ ]:
#Bài 2:
import numpy as np
#Ma trận phân kỳ:
A = np.array([[0, 1], [1, 0]])
print(A)
print('---')

temp = A.dot(A)
print(temp)
print('---')

k = 6
for i in range(k - 1):
    temp = temp.dot(A)
    print(temp)
    print('---')

B = np.array([[0, -1], [-1, 0]])
print(B)
print('---')

temp = B.dot(B)
print(temp)
print('---')

k = 5
for i in range(k - 1):
    temp = temp.dot(B)
    print(temp)
    print('---')


[[0 1]
 [1 0]]
---
[[1 0]
 [0 1]]
---
[[0 1]
 [1 0]]
---
[[1 0]
 [0 1]]
---
[[0 1]
 [1 0]]
---
[[1 0]
 [0 1]]
---
[[0 1]
 [1 0]]
---
[[ 0 -1]
 [-1  0]]
---
[[1 0]
 [0 1]]
---
[[ 0 -1]
 [-1  0]]
---
[[1 0]
 [0 1]]
---
[[ 0 -1]
 [-1  0]]
---
[[1 0]
 [0 1]]
---


In [ ]:
#Ma trận hội tụ - Convergent matrix:
import numpy as np

C = np.array([ [1, 0, 0], [0, 0.5, 1], [0, 0, 0.5] ])
print(C)
print('---')

temp = C.dot(C)
print(temp)
print('---')

k = 1000
for i in range(k-1):
    temp = temp.dot(C)
print(temp)
print('---')

for i in range(k-1):
    temp = temp.dot(C)
print(temp)
print('---')


[[1.  0.  0. ]
 [0.  0.5 1. ]
 [0.  0.  0.5]]
---
[[1.   0.   0.  ]
 [0.   0.25 1.  ]
 [0.   0.   0.25]]
---
[[1.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 4.66631809e-302 9.34196882e-299]
 [0.00000000e+000 0.00000000e+000 4.66631809e-302]]
---
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
---


In [ ]:
#Ma trận Markov
import numpy as np

M = np.array([[0.8, 0.3], [0.2, 0.7]])
MM = M.dot(M)  # M^2
print(MM)
print('---')

MM = MM.dot(M)  # M^3
print(MM)
print('---')

for i in range(100):
    MM = MM.dot(M)
print(MM)
print('---')

M = np.array([[0.5, 0.5], [0.5, 0.5]])
MM = M.dot(M)  # M^2
print(MM)
print('---')

MM = MM.dot(M)  # M^3
print(MM)
print('---')

for i in range(100):
    MM = MM.dot(M)
print(MM)
print('---')


[[0.7  0.45]
 [0.3  0.55]]
---
[[0.65  0.525]
 [0.35  0.475]]
---
[[0.6 0.6]
 [0.4 0.4]]
---
[[0.5 0.5]
 [0.5 0.5]]
---
[[0.5 0.5]
 [0.5 0.5]]
---
[[0.5 0.5]
 [0.5 0.5]]
---


In [ ]:
#Bài 3:
import numpy as np
from scipy import linalg

M = np.array([[0.8, 0.3], [0.2, 0.7]])
P, L, U = linalg.lu(M)
print(P)
print('---')
print(L)
print('---')
print(U)
print('---')
print(L.dot(U))

[[1. 0.]
 [0. 1.]]
---
[[1.   0.  ]
 [0.25 1.  ]]
---
[[0.8   0.3  ]
 [0.    0.625]]
---
[[0.8 0.3]
 [0.2 0.7]]


In [ ]:
#Bài 5-Bài toán ứng dụng 2 – Bài toán loan tin :
import numpy as np
A = np.array([[0, 1, 0, 1], [0, 0, 1, 0], [1, 0, 0, 1], [1, 1, 0, 0]])
sumA = A
temp = A.dot(A)
k = 3
sumA = sumA + temp
for i in range(1, k - 1):
    temp = temp.dot(A)
    sumA = sumA + temp
print(temp)
print('---')
print(sumA)

[[1 1 1 2]
 [1 2 0 1]
 [1 2 2 1]
 [2 1 1 1]]
---
[[2 3 2 3]
 [2 2 1 2]
 [3 4 2 3]
 [3 3 2 2]]


# **Bài Tập Chương **

In [2]:
#Câu 1:
import numpy as np

ma_tran = np.array([[2, 1, 1],
                    [1, 3, 1],
                    [1, 1, 2]])

dinh_thuc = np.linalg.det(ma_tran)
print("Định thức của ma trận:", round(dinh_thuc, 2))
assert dinh_thuc != 0, "Ma trận không khả nghịch!"

chuoi_goc = input("Nhập họ tên hoặc MSSV: ")
mang_ma_ascii = [ord(ky_tu) for ky_tu in chuoi_goc]

while len(mang_ma_ascii) % 3 != 0:
    mang_ma_ascii.append(0)

danh_sach_vector = [mang_ma_ascii[i:i+3] for i in range(0, len(mang_ma_ascii), 3)]
danh_sach_ma_hoa = [np.dot(ma_tran, np.array(vec)) for vec in danh_sach_vector]

print("\nDữ liệu đã mã hóa:")
for v in danh_sach_ma_hoa:
    print(v)

ma_tran_nghich_dao = np.linalg.inv(ma_tran)
danh_sach_giai_ma = [np.dot(ma_tran_nghich_dao, v).round().astype(int) for v in danh_sach_ma_hoa]

chuoi_giai_ma = ''.join([chr(gia_tri) for v in danh_sach_giai_ma for gia_tri in v if gia_tri != 0])
print("\nGiải mã được:")
print(chuoi_giai_ma)


Định thức của ma trận: 7.0
Nhập họ tên hoặc MSSV: 2474802010440

Dữ liệu đã mã hóa:
[207 261 212]
[208 268 204]
[197 243 196]
[200 256 204]
[96 48 48]

Giải mã được:
2474802010440


In [3]:
#Câu 2:
#a:
import numpy as np
def tinh_phan_so(danh_sach_c):
    M = np.array([[danh_sach_c[0], 1], [1, 0]], dtype=int)
    for c in danh_sach_c[1:]:
        M = np.dot(M, np.array([[c, 1], [1, 0]], dtype=int))
    return M[0][0], M[1][0]
ds = [3, 1, 2]
p, q = tinh_phan_so(ds)
print(f"Phân số: {p}/{q}")

Phân số: 11/3


b.Chứng minh:

Cơ sở với
𝑛
=
0
n=0:

[
𝑝
0
𝑞
0
]
=
[
𝑐
0
1
1
0
]
⋅
[
1
0
]
=
[
𝑐
0
1
]
⇒
𝑝
0
=
𝑐
0
,
𝑞
0
=
1
[
p
0
​

q
0
​

​
 ]=[
c
0
​

1
​
  
1
0
​
 ]⋅[
1
0
​
 ]=[
c
0
​

1
​
 ]⇒p
0
​
 =c
0
​
 ,q
0
​
 =1
Giả sử đúng với n-1, tức là:

[
𝑝
𝑛
−
1
𝑞
𝑛
−
1
]
=
𝐴
𝑛
−
1
⋅
[
1
0
]
[
p
n−1
​

q
n−1
​

​
 ]=A
n−1
​
 ⋅[
1
0
​
 ]
Bước quy nạp:
Nhân thêm ma trận
𝐴
𝑛
=
[
𝑐
𝑛
1
1
0
]
A
n
​
 =[
c
n
​

1
​
  
1
0
​
 ] vào ta có:

[
𝑝
𝑛
𝑞
𝑛
]
=
𝐴
0
𝐴
1
⋯
𝐴
𝑛
⋅
[
1
0
]
[
p
n
​

q
n
​

​
 ]=A
0
​
 A
1
​
 ⋯A
n
​
 ⋅[
1
0
​
 ]