In [2]:
#Bài 1:
#1.1:
import numpy as np

#D = np.array([[1, 2], [3, 4]])
#np.copyto(E, D)  # lỗi vì E chưa được khai báo

E = np.array([[1, 2], [3, 5]])
np.copyto(E, D)
print(E)


[[1 2]
 [3 4]]


In [5]:
#1.2:
# Nên sử dụng kiểu numpy.matrix:
import numpy as np
# x = np.array([['a','b'],['c','d']])  # Dòng này gây lỗi vì np.matrix cần dữ liệu số
# y = 'x'                              # Dòng này cũng gây lỗi vì y là chuỗi
# Thay x và y bằng giá trị số vì np.matrix yêu cầu dữ liệu số
x_so = 10
y_so = 20
# Tạo ma trận với giá trị số
C = np.matrix([[x_so, y_so], [1, 2]])
print(C)

[[10 20]
 [ 1  2]]


In [6]:
#Không nên/thể sử dụng kiểu numpy.matrix:
import numpy as np
#A = np.matrix([[[1,2],[3,4]],[[5,6],[7,8]]])  # lỗi vì numpy.matrix chỉ hỗ trợ 2 chiều

A = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(A)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [7]:
#1.3:
from numpy import matlib

G = matlib.identity(5)
print(G)
H = matlib.randn(3, 2)
print(H)
K = matlib.zeros([4, 4])
print(K)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[-0.42364742  0.34807829]
 [ 1.51622195 -0.76913553]
 [ 0.96069799 -1.09466671]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
#Bài 2:
import numpy as np

c = [3, 7, 15, 1, 292, 1, 1, 1, 2, 1, 3, 1, 14, 2]
# Thay np.mat bằng np.asmatrix vì np.mat đã bị xóa trong NumPy 2.0
M = np.asmatrix([[1, 2], [3, 4]])
for i in range(len(c)):
    # Thay np.mat bằng np.asmatrix
    ci = np.asmatrix([[1, 1], [1, 0]])
    ci[0, 0] = c[i]
    if i == 0:
        M = ci
    else:
        M = M.dot(ci)
print(M)
print(M[0, 0] / M[1, 0])

[[165707065  80143857]
 [ 52746197  25510582]]
3.1415926535897936


In [12]:
#Bài 3:
X = np.array([[1, 1], [1, 2], [1, 3], [1, 4], [1, 5]])
Y = np.array([[2], [4], [4], [4], [6]])
XT = X.T
A1 = np.linalg.inv(XT.dot(X))  # (X^T X)^(-1)
A2 = XT.dot(Y)                 # X^T Y
A = A1.dot(A2)
f = X.dot(A)  # f_i = a0 + a1*x_i
error = f - Y
total_squared_error = (error.T).dot(error)
print(f"Hệ số hồi quy: a0 = {A[0][0]:.2f}, a1 = {A[1][0]:.2f}")
print(f"Phương trình: y = {A[0][0]:.2f} + {A[1][0]:.2f}x")
print(f"Tổng bình phương sai số: {total_squared_error[0][0]:.2f}")

Hệ số hồi quy: a0 = 1.60, a1 = 0.80
Phương trình: y = 1.60 + 0.80x
Tổng bình phương sai số: 1.60


# **--Bài Tập Chương--**

In [11]:
#Câu 1:
import numpy as np
from numpy import linalg
def bpcuctieu(a):
    b = []
    o1 = []
    for i in range(len(a)):
        o1.append(1.0)
        b.append((i + 1) * 1.0)
    x = np.array([o1, b])
    u = np.dot(x, x.T)
    y = np.array(a)
    u_1 = np.linalg.inv(u)
    v = np.dot(u_1, x)
    A = np.dot(v, y)
    return A
dulieu = [10.0, 8, 7, 5, 2]
kq = bpcuctieu(dulieu)
print(f"Phương trình: y = {kq[0]:.1f} + {kq[1]:.1f}x")

Phương trình: y = 12.1 + -1.9x
