[link text](https://)

In [ ]:
#Bai1:
def scale(a, v):
 return [a*vi for vi in v]
v = [3,5,7]
print(scale(10, v))
def sumvector(v, w):
 return [vi+wi for (vi, wi) in zip(v, w)]
v = [3,5,7]
w = [2,4,6]
print(sumvector(v, w))
def dotvector(v, w):
 return sum([vi*wi for (vi, wi) in zip(v, w)])
print(dotvector(v, w))
def lenvector(v):
 return dotvector(v,v)
print(lenvector(w))


[30, 50, 70]
[5, 9, 13]
68
56


In [ ]:
#Bai2:
import numpy as np
scores = np.array([-1, 1, 2, -3, 5, -4])
print(np.select([scores >= 0, scores < 0], ['so duong', 'so am'], default=''))
scores = np.array([-1, 1, 2, 0, -3, 5, 0, -4])
print(np.select([scores > 0, scores == 0, scores < 0], ['so duong', 'so 0', 'so am'], default=''))

['so am' 'so duong' 'so duong' 'so am' 'so duong' 'so am']
['so am' 'so duong' 'so duong' 'so 0' 'so am' 'so duong' 'so 0' 'so am']


In [ ]:
#Bai3:
#3.1:
import numpy as np
from scipy import linalg, sparse
# 2
D = np.asmatrix([[3, 4], [5, 6]])
print(D)
# 3
C = np.asmatrix(np.random.random((5, 7)))
print(C)

# 4
A = np.asmatrix(np.random.random((2, 2)))
print(A)
# 5
b = np.array([(1 + 5j, 2j, 3j), (4, 5, 6)])
B = np.asmatrix(b)
print(b)
print(B)
# 6
print(A.T)
# 7
print(A.I)
print(linalg.inv(A))
# 8
M = np.array([[-1, 3, 2], [0, -2, 1], [1, 5, -2]])
M_lower = np.tril(M)
print(M_lower)
# 9
M_upper = np.triu(M)
print(M_upper)
# 10
v_diag = np.diag(M)
print(v_diag)
M_diag = np.diag(v_diag)
print(M_diag)

[[3 4]
 [5 6]]
[[0.55413326 0.87716722 0.01509562 0.19195871 0.70325486 0.30573007
  0.95736472]
 [0.78289977 0.96779726 0.78347797 0.85138094 0.93885269 0.4859564
  0.88639728]
 [0.73686286 0.41950494 0.54537931 0.91792671 0.18436155 0.56973892
  0.71964936]
 [0.16239293 0.35921541 0.04710927 0.40655945 0.22265643 0.11617501
  0.12137645]
 [0.43375572 0.04934332 0.64037212 0.09168932 0.05772463 0.70146778
  0.30164176]]
[[0.10424474 0.76281741]
 [0.31972494 0.0612675 ]]
[[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]
[[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]
[[0.10424474 0.31972494]
 [0.76281741 0.0612675 ]]
[[-0.25796305  3.21179598]
 [ 1.34618229 -0.4389161 ]]
[[-0.25796305  3.21179598]
 [ 1.34618229 -0.4389161 ]]
[[-1  0  0]
 [ 0 -2  0]
 [ 1  5 -2]]
[[-1  3  2]
 [ 0 -2  1]
 [ 0  0 -2]]
[-1 -2 -2]
[[-1  0  0]
 [ 0 -2  0]
 [ 0  0 -2]]


In [1]:
#Bài 3.2
import numpy as np

A = np.reshape(np.arange(36.0), (6, 6))
print(A)

I6 = np.identity(6)
print(I6)

print(A.size)
print(A.diagonal())

A = A + I6
print(A)

vecB = np.array([1., 2., 3., 4., 5., 6.])
C = A.dot(vecB)
print(C)

D = np.array([
    [1., 2., 3., 4., 5., 6.],
    [1., 0., 1., 0., 1., 0.]
])
print(D)

E = A.dot(D.T)
print(E)

F = np.array([
    [1., 1.],
    [2., 0.],
    [3., 1.],
    [4., 0.],
    [5., 1.],
    [6., 0.]
])
print(F)

G = A.dot(F)
print(G)

invA = np.linalg.inv(A)
print(invA)

inv_inv_A = np.linalg.inv(invA)
print(inv_inv_A)


[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35.]]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
36
[ 0.  7. 14. 21. 28. 35.]
[[ 1.  1.  2.  3.  4.  5.]
 [ 6.  8.  8.  9. 10. 11.]
 [12. 13. 15. 15. 16. 17.]
 [18. 19. 20. 22. 22. 23.]
 [24. 25. 26. 27. 29. 29.]
 [30. 31. 32. 33. 34. 36.]]
[ 71. 198. 325. 452. 579. 706.]
[[1. 2. 3. 4. 5. 6.]
 [1. 0. 1. 0. 1. 0.]]
[[ 71.   7.]
 [198.  24.]
 [325.  43.]
 [452.  60.]
 [579.  79.]
 [706.  96.]]
[[1. 1.]
 [2. 0.]
 [3. 1.]
 [4. 0.]
 [5. 1.]
 [6. 0.]]
[[ 71.   7.]
 [198.  24.]
 [325.  43.]
 [452.  60.]
 [579.  79.]
 [706.  96.]]
[[ 0.37022901 -0.45610687 -0.28244275 -0.10877863  0.0648855   0.23854962]
 [-0.44656489  0.65839695 -0.23664122 -0.13167939 -0.02671756  0.07824427]
 [-0.26335878 -0.22709924  0.80916031 -0.15458015 -0.11832061 -0.08206107]
 [-0.

In [2]:
#Bài 4:
import numpy as np

A = np.array([[1, 1], [1, 0]])
b = np.array([1, 0])
n = 10

for i in range(n):
    b = A.dot(b)
    print(b)


[1 1]
[2 1]
[3 2]
[5 3]
[8 5]
[13  8]
[21 13]
[34 21]
[55 34]
[89 55]


In [7]:
#Bài 5:
import sympy as sp
from sympy import Symbol, solve

x1 = Symbol('x1')
x2 = Symbol('x2')
x3 = Symbol('x3')
x4 = Symbol('x4')

pt1 = x4 + 610 - 450 - x1
pt2 = x1 + 400 - x2 - 640
pt3 = x2 + 600 - x3
pt4 = x3 - x4 - 520

nghiem = sp.solve((pt1, pt2, pt3, pt4))
print(nghiem)

{x1: x4 + 160, x2: x4 - 80, x3: x4 + 520}


# **Bài Tập Chương **

In [10]:
#Câu 1:
#1
import numpy as np

A1 = np.array([[1, -1], [2, 3]])
b1 = np.array([-2, 6])

x1 = np.linalg.solve(A1, b1)
print(x1)
#2
A2 = np.array([[1, -1, 0], [2, -1, -1], [1, 1, 1]])
b2 = np.array([2, 3, 6])

x2 = np.linalg.solve(A2, b2)
print(x2)
#3
A3 = np.array([[1, 1, 1], [4, 2, 1], [9, 3, 1]])
b3 = np.array([4, 3, 4])

x3 = np.linalg.solve(A3, b3)
print(x3)
#4
A4 = np.array([[1, 0, 1], [1, -2, 1], [-2, 2, 0]])
b4 = np.array([1, -3, 0])

x4 = np.linalg.solve(A4, b4)
print(x4)




[0. 2.]
[3. 1. 2.]
[ 1. -4.  7.]
[ 2.  2. -1.]


In [11]:
#câu 2:
#1
import sympy as sp

x, y = sp.symbols('x y')

eq1 = x - y + 2
eq2 = 2*x + 3*y - 6

sol1 = sp.solve((eq1, eq2), (x, y))
print(sol1)
#2
x, y, z = sp.symbols('x y z')

eq1 = x - y - 2
eq2 = 2*x - y - z - 3
eq3 = x + y + z - 6

sol2 = sp.solve((eq1, eq2, eq3), (x, y, z))
print(sol2)
#3
a, b, c = sp.symbols('a b c')

eq1 = a + b + c - 4
eq2 = 4*a + 2*b + c - 3
eq3 = 9*a + 3*b + c - 4

sol3 = sp.solve((eq1, eq2, eq3), (a, b, c))
print(sol3)
#4
a, b, c = sp.symbols('a b c')

eq1 = a + c - 1
eq2 = a + b - 2*c + 3
eq3 = -2*a + 2*b + c

sol4 = sp.solve((eq1, eq2, eq3), (a, b, c))
print(sol4)


{x: 0, y: 2}
{x: 3, y: 1, z: 2}
{a: 1, b: -4, c: 7}
{a: -1/9, b: -2/3, c: 10/9}


In [12]:
#Câu 3:
# SymPy
from sympy import Matrix,symbols,simplify
k=symbols('k',integer=True,positive=True)
F=Matrix([[1,1],[1,0]])
F_k=F**k
print("Dạng tổng quát của F^k:")
display(F_k)

#NumPy
import numpy as np
def fibonacci_matrix(k):
    F=np.array([[1,1],[1,0]])
    return np.linalg.matrix_power(F,k)
k=5
F_5=fibonacci_matrix(k)
print(f"\nMa trận F^{k}:")
print(F_5)

Dạng tổng quát của F^k:


Matrix([
[-(-5 + sqrt(5))*(1/2 - sqrt(5)/2)**k/((-5 + 5*sqrt(5))*(1/2 + sqrt(5)/2)) - sqrt(5)*(1/2 + sqrt(5)/2)**k/(5*(1/2 - sqrt(5)/2)), -(1/2 - sqrt(5)/2)**k*(sqrt(5)/10 + 1/2)/(1/2 + sqrt(5)/2) - 2*sqrt(5)*(1/2 + sqrt(5)/2)**k/((1/2 - sqrt(5)/2)*(5 + 5*sqrt(5)))],
[                                         (-5 + sqrt(5))*(1/2 - sqrt(5)/2)**k/(-5 + 5*sqrt(5)) + sqrt(5)*(1/2 + sqrt(5)/2)**k/5,                                        (1/2 - sqrt(5)/2)**k*(sqrt(5)/10 + 1/2) + 2*sqrt(5)*(1/2 + sqrt(5)/2)**k/(5 + 5*sqrt(5))]])


Ma trận F^5:
[[8 5]
 [5 3]]
